# $FreeBSD$

MASTERDIR=	${.CURDIR}/../Kontrol-pkg-zabbix-proxy

PORTNAME=	Kontrol-pkg-zabbix-proxy44

CONFLICTS=	Kontrol-pkg-zabbix-proxy \
		Kontrol-pkg-zabbix-proxy4 \
		Kontrol-pkg-zabbix-proxy5

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix44-proxy

ZABBIXINTERNALNAME=	zabbix-proxy44
ZABBIXTITLE=	Zabbix Proxy 4.4
ZABBIXVERSION=	44

.include "${MASTERDIR}/Makefile"
