# $FreeBSD

MASTERDIR=	${.CURDIR}/../Kontrol-pkg-zabbix-agent

PORTNAME=	Kontrol-pkg-zabbix-agent44

CONFLICTS=	Kontrol-pkg-zabbix-agent \
		Kontrol-pkg-zabbix-agent4 \
		Kontrol-pkg-zabbix-agent5

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix44-agent

ZABBIXINTERNALNAME=	zabbix-agent44
ZABBIXTITLE=	Zabbix Agent 4.4
ZABBIXVERSION=	44

.include "${MASTERDIR}/Makefile"
