# $FreeBSD$

MASTERDIR=	${.CURDIR}/../Kontrol-pkg-zabbix-proxy

PORTNAME=	Kontrol-pkg-zabbix-proxy4

CONFLICTS=	Kontrol-pkg-zabbix-proxy \
		Kontrol-pkg-zabbix-proxy44 \
		Kontrol-pkg-zabbix-proxy5

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix4-proxy

ZABBIXINTERNALNAME=	zabbix-proxy4
ZABBIXTITLE=	Zabbix Proxy 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
