# $FreeBSD$

MASTERDIR=	${.CURDIR}/../Kontrol-pkg-zabbix-proxy

PORTNAME=	Kontrol-pkg-zabbix-proxy5

CONFLICTS=	Kontrol-pkg-zabbix-proxy \
		Kontrol-pkg-zabbix-proxy4 \
		Kontrol-pkg-zabbix-proxy44

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix5-proxy

ZABBIXINTERNALNAME=	zabbix-proxy5
ZABBIXTITLE=	Zabbix Proxy 5.0
ZABBIXVERSION=	50

.include "${MASTERDIR}/Makefile"
