# $FreeBSD

MASTERDIR=	${.CURDIR}/../Kontrol-pkg-zabbix-agent

PORTNAME=	Kontrol-pkg-zabbix-agent5

CONFLICTS=	Kontrol-pkg-zabbix-agent \
		Kontrol-pkg-zabbix-agent4 \
		Kontrol-pkg-zabbix-agent44

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix5-agent

ZABBIXINTERNALNAME=	zabbix-agent5
ZABBIXTITLE=	Zabbix Agent 5.0
ZABBIXVERSION=	50

.include "${MASTERDIR}/Makefile"
