# $FreeBSD$

MASTERDIR=	${.CURDIR}/../Kontrol-pkg-zabbix-agent

PORTNAME=	Kontrol-pkg-zabbix-agent4

CONFLICTS=	Kontrol-pkg-zabbix-agent \
		Kontrol-pkg-zabbix-agent44 \
		Kontrol-pkg-zabbix-agent5

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix4-agent

ZABBIXINTERNALNAME=	zabbix-agent4
ZABBIXTITLE=	Zabbix Agent 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
